services:
  php:
    build: php
    ports:
    - "8981:80" # port where webpage will be accessible (8180)
    - "8943:443"
    volumes:
    - ./php/www/:/var/www/html
    links:
    - db

  db:
    image: mysql:latest
    env_file: .env
    volumes:
    - ./mysql/database:/var/lib/mysql
    - ./mysql:/docker-entrypoint-initdb.d
    - ./data:/var/lib/mysql-files
    environment:
    - PUID=${PUID}
    - GUID=${GUID}
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
    - "33061:3306" # maps container's 3306 to host's 33060 (to access via phpmyadmin)

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    env_file: .env
    restart: always
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "8982:80"