"""changed phone column

Revision ID: 11790ac878f5
Revises: c7771eefad7a
Create Date: 2025-03-10 04:35:50.889298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11790ac878f5'
down_revision = 'c7771eefad7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
        batch_op.alter_column('zip',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('phone1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone1', sa.VARCHAR(length=20), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('zip',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
