"""removed unique email constraint

Revision ID: c7771eefad7a
Revises: 7f965a1cd537
Create Date: 2025-03-10 02:21:43.030862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7771eefad7a'
down_revision = '7f965a1cd537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index('ix_customer_email')
        batch_op.create_index(batch_op.f('ix_customer_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_email'))
        batch_op.create_index('ix_customer_email', ['email'], unique=1)

    # ### end Alembic commands ###
